### PR TITLE
feat(brand): add clear button to theme color picker

### PR DESCRIPTION
**Pull request by kariae**

### CODE REVIEW

**Comment by leogermani** [comment]
@kariae I realized that we were displaying `#fff` when the color was null. That was not correct.

I tweaked the code to make sure we delete the color from the meta when we reset defaults, and also we display the theme defaults color when the meta is empty. Have a look.

Bonus: https://github.com/Automattic/newspack-theme/pull/2102

**Comment by kariae** [comment]
@leogermani that's amazing, resetting the colors to the default theme settings is much better than an #fff. Looks good to me, do you want me to approve the bonus PR, looks good to me too.

A quick note about [this](https://github.com/Automattic/newspack-multibranded-site/pull/21/files#diff-983d1af6904806fa07c30c4ab189330a11f25f2f8019c068df1e557e4500515aR72) I don't think we need it since if a color doesn't exist in the theme it won't be usable, no?

**Comment by leogermani** [comment]
> A quick note about [this](https://github.com/Automattic/newspack-multibranded-site/pull/21/files#diff-983d1af6904806fa07c30c4ab189330a11f25f2f8019c068df1e557e4500515aR72) I think we can skip adding a color, since if a color doesn't exist in the theme it won't be usable, no?

"Adding" there means adding to the meta_value array. It's exactly you were already doing [here](https://github.com/Automattic/newspack-multibranded-site/pull/21/files#diff-983d1af6904806fa07c30c4ab189330a11f25f2f8019c068df1e557e4500515aL51). I just expanded the logic to cover other cases

**Review by leogermani — APPROVED** [review]

**Comment by kariae** [comment]
Thanks @leogermani all good here.

**Pull request merged**
