### PR TITLE
feat: add menu options to the UI

### PR DESCRIPTION
**Pull request by leogermani**
* Create 2 menus
* Apply one menu to the primary menu location
* Edit a brand
* Select the other menu to be displayed in the primary menu location
* Check and see if it works
* Try setting the menu back to the "same as site"
* See if it works
* try to break things

### CODE REVIEW

**Comment by leogermani** [comment]
> I have an issue when setting back the menu as same as site, the menu is not shown,

Do you have a menu configured for that position? In Appearance > Menus > Manage Locations. "Same as site" means it will display whatever is there

**Comment by kariae** [comment]
So the two menus I have are setup like this:
Menu 1: Primary Menu, Secondary Menu
Menu 2: Tertiary Menu

Menu 1 is technically the site menu if I understand this correctly (I'm not that good with menus in WP 😅) 

When I set Menu 1 or Menu 2 as a primary menu to my brand, they both show up fine, but when I set it as `same as site` no menu is shown in the primary menu place.

**Comment by leogermani** [comment]
ah, yes. I see it now, my bad. Fix is on the way

**Review by kariae — APPROVED** [review]
Works like a charm

**Pull request merged**
